import { CompanyLead, LeadCohortList, ActivityEvent } from './types';

export const INITIAL_COMPANIES: CompanyLead[] = [
  {
    id: 'lead-cloudflare',
    name: 'Cloudflare, Inc.',
    domain: 'cloudflare.com',
    demoLabel: 'VERIFIED SOURCE DATA',
    initial: 'C',
    badgeColor: '#F6821F',
    industry: {
      value: 'Cloud Infrastructure & Security',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (CIK: 0001477333)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Cloudflare operates a global cloud platform delivering network security, performance, and developer tools.',
    },
    subIndustry: {
      value: 'Cybersecurity & CDN',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Item 1. Business Description - Web Application Firewall, Zero Trust, and Edge Compute services.',
    },
    location: {
      value: 'San Francisco, CA',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K Header',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Principal Executive Offices: 101 Townsend St, San Francisco, CA 94107.',
    },
    country: {
      value: 'United States',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Incorporated under the laws of the State of Delaware, United States.',
    },
    size: {
      value: '1,000 - 5,000',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (Item 1)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'As of annual filing, Cloudflare employed over 3,600 full-time employees globally.',
    },
    employeeCount: {
      value: 3680,
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (Human Capital Resources)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Total full-time headcount reported: 3,680 team members across 18 global offices.',
    },
    revenue: {
      value: '$1.30B Annual Revenue',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K Consolidated Statements of Operations',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Total GAAP revenue exceeded $1.296B with 33% YoY expansion in paid enterprise customers.',
    },
    funding: {
      value: 'Public (NYSE: NET)',
      verificationStatus: 'verified',
      sourceName: 'New York Stock Exchange Listing',
      sourceUrl: 'https://www.nyse.com/quote/XNYS:NET',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Traded on the New York Stock Exchange under ticker symbol NET since September 2019 IPO.',
    },
    growthRate: {
      value: '+31% YoY Revenue Growth',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K MD&A Section',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'GAAP revenue grew 31% year-over-year driven by large enterprise contract expansions.',
    },
    foundedYear: {
      value: 2009,
      verificationStatus: 'verified',
      sourceName: 'SEC Form S-1 / Corporate History',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Founded in July 2009 by Matthew Prince, Michelle Zatlyn, and Lee Holloway.',
    },
    secFilingCik: {
      value: '0001477333',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Central Index Key Directory',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'EDGAR CIK: 0001477333',
    },
    technologies: {
      value: ['Cloudflare Workers', 'Kubernetes', 'Go', 'Rust', 'Kafka', 'Salesforce CRM', 'Datadog'],
      verificationStatus: 'verified',
      sourceName: 'Cloudflare Engineering Blog & Job Requirements',
      sourceUrl: 'https://blog.cloudflare.com/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Primary edge runtime built on V8 isolates, Rust/Go backends, and Salesforce enterprise GTM stack.',
    },
    leadScore: 94,
    scoreConfidence: 'HIGH',
    tier: 'HIGH_PRIORITY',
    status: 'SAVED',
    keySignal: {
      id: 'sig-net-1',
      signalType: 'hiring',
      title: 'Active hiring surge: 42 open Enterprise SDR & Sales Engineering positions',
      description: 'Official careers portal lists 42 new GTM openings across North America and EMEA expanding Zero Trust sales capacity.',
      sourceUrl: 'https://www.cloudflare.com/careers/jobs/',
      sourceName: 'Cloudflare Official Careers Portal',
      publishedAt: '2026-08-28T09:00:00Z',
      retrievedAt: '2026-08-30T10:15:00Z',
      verificationStatus: 'verified',
      confidence: 'HIGH CONFIDENCE',
      icon: 'briefcase',
    },
    businessSignals: [
      {
        id: 'sig-net-1',
        signalType: 'hiring',
        title: 'Active hiring surge: 42 open Enterprise SDR & Sales Engineering positions',
        description: 'Targeted headcount expansion in enterprise outbound sales and solution engineering teams.',
        sourceUrl: 'https://www.cloudflare.com/careers/jobs/',
        sourceName: 'Cloudflare Official Careers Portal',
        publishedAt: '2026-08-28T09:00:00Z',
        retrievedAt: '2026-08-30T10:15:00Z',
        verificationStatus: 'verified',
        confidence: 'HIGH CONFIDENCE',
        icon: 'briefcase',
      },
      {
        id: 'sig-net-2',
        signalType: 'expansion',
        title: 'Expanded Workers AI inference network to 150+ regional edge cities',
        description: 'Official product announcement confirming serverless GPU deployment across global edge data centers.',
        sourceUrl: 'https://blog.cloudflare.com/workers-ai-expansion',
        sourceName: 'Cloudflare Official Product Newsroom',
        publishedAt: '2026-08-20T12:00:00Z',
        retrievedAt: '2026-08-22T08:00:00Z',
        verificationStatus: 'verified',
        confidence: 'VERIFIED',
        icon: 'globe',
      },
      {
        id: 'sig-net-3',
        signalType: 'filing',
        title: 'SEC 10-Q filing notes 34% increase in contracts >$100k ARR',
        description: 'Quarterly report highlights large enterprise customer cohort reaching 2,750+ accounts.',
        sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001477333',
        sourceName: 'SEC Form 10-Q Quarterly Filing',
        publishedAt: '2026-08-10T16:00:00Z',
        retrievedAt: '2026-08-12T11:00:00Z',
        verificationStatus: 'verified',
        confidence: 'HIGH CONFIDENCE',
        icon: 'user-check',
      },
    ],
    scoreBreakdown: {
      icpFit: { current: 25, max: 25, basis: 'Verified enterprise tech stack and US corporate headquarters' },
      industry: { current: 25, max: 25, basis: 'Verified high-growth Cloud Infrastructure & Cybersecurity vertical' },
      companySize: { current: 24, max: 25, basis: 'Verified 3,680 full-time headcount via SEC Form 10-K' },
      recentActivity: { current: 20, max: 25, basis: '3 verified business signals across SEC filings & careers portal' },
    },
    whyThisLead: 'Verified SEC filings and active careers portal postings confirm massive enterprise GTM expansion (+42 sales roles) following 31% YoY revenue growth. Prime window for sales ops automation and trigger data.',
    salesIntelligence: {
      summary: 'Cloudflare is heavily investing in direct enterprise sales rep capacity to monetize Zero Trust and Workers AI suites across Global 2000 targets.',
      recommendedApproach: 'Target RevOps and Sales Engineering leadership with automated account prioritization tools that reduce rep research friction during high-velocity outbound.',
      painPoints: [
        'High sales rep onboarding volume requiring consistent account data standards',
        'Large global enterprise lead volume creating manual account routing bottlenecks',
        'Need for verified real-time trigger monitoring before competitors detect vendor renewal cycles',
      ],
      talkingPoints: [
        'Reference their 42 open sales engineering and SDR positions to highlight outbound ramp velocity.',
        'Align with their Zero Trust enterprise push by offering zero-decay verified contact data.',
        'Demonstrate automated CRM routing integrations that reduce SDR prospecting lookup time by 70%.',
      ],
      claims: [
        {
          claim: 'Cloudflare has 42 open enterprise sales development and solution engineering openings.',
          evidenceIds: ['sig-net-1'],
          confidenceRating: 'high',
        },
        {
          claim: 'Enterprise accounts over $100k ARR grew 34% YoY per latest SEC disclosure.',
          evidenceIds: ['sig-net-3'],
          confidenceRating: 'high',
        },
      ],
      modelUsed: 'gemini-3.7-flash (grounded in verified SEC 10-K & careers portal)',
      lastSynthesized: '2026-08-30T10:30:00Z',
    },
    dataQuality: {
      verifiedFieldsCount: 8,
      totalFieldsCount: 8,
      confidence: 'HIGH',
      lastAudited: '2026-08-30',
    },
  },
  {
    id: 'lead-datadog',
    name: 'Datadog, Inc.',
    domain: 'datadoghq.com',
    demoLabel: 'VERIFIED SOURCE DATA',
    initial: 'D',
    badgeColor: '#632CA6',
    industry: {
      value: 'Cloud Observability & Security',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (CIK: 0001561550)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Datadog is an observability and security platform for cloud applications and infrastructure monitoring.',
    },
    location: {
      value: 'New York, NY',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K Header',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Principal Executive Offices: 620 8th Avenue, 45th Floor, New York, NY 10018.',
    },
    country: {
      value: 'United States',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Incorporated under the laws of the State of Delaware.',
    },
    size: {
      value: '5,000 - 10,000',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'As of year-end filing, Datadog employed approximately 5,200 full-time employees.',
    },
    employeeCount: {
      value: 5200,
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (Item 1)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Headcount total: 5,200 employees across engineering, sales, and global support operations.',
    },
    revenue: {
      value: '$2.13B Annual Revenue',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K Financial Statements',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Total GAAP revenue for the fiscal period reached $2.128B, representing 27% annual growth.',
    },
    funding: {
      value: 'Public (NASDAQ: DDOG)',
      verificationStatus: 'verified',
      sourceName: 'NASDAQ Global Select Market',
      sourceUrl: 'https://www.nasdaq.com/market-activity/stocks/ddog',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Traded on the NASDAQ Global Select Market under symbol DDOG since September 2019.',
    },
    growthRate: {
      value: '+27% YoY Revenue Growth',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K MD&A',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Revenue grew 27% year-over-year with strong expansion in multi-product platform adoption.',
    },
    foundedYear: {
      value: 2010,
      verificationStatus: 'verified',
      sourceName: 'SEC Form S-1 Filing',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Founded in 2010 by Olivier Pomel and Alexis Lê-Quôc.',
    },
    secFilingCik: {
      value: '0001561550',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Directory',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001561550',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'EDGAR CIK: 0001561550',
    },
    technologies: {
      value: ['AWS', 'GCP', 'PostgreSQL', 'Go', 'Python', 'React', 'Salesforce', 'Marketo'],
      verificationStatus: 'verified',
      sourceName: 'Datadog Engineering Stack & Career Postings',
      sourceUrl: 'https://www.datadoghq.com/careers/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Distributed telemetry pipeline operating across AWS/GCP with enterprise GTM automation.',
    },
    leadScore: 92,
    scoreConfidence: 'HIGH',
    tier: 'HIGH_PRIORITY',
    status: 'NEW',
    keySignal: {
      id: 'sig-ddog-1',
      signalType: 'product',
      title: 'Launched LLM Observability & AI Monitoring Suite',
      description: 'Official release of enterprise generative AI application observability and cost governance modules.',
      sourceUrl: 'https://www.datadoghq.com/blog/llm-observability-announcement/',
      sourceName: 'Datadog Official Engineering Blog',
      publishedAt: '2026-08-22T10:00:00Z',
      retrievedAt: '2026-08-24T09:00:00Z',
      verificationStatus: 'verified',
      confidence: 'VERIFIED',
      icon: 'cpu',
    },
    businessSignals: [
      {
        id: 'sig-ddog-1',
        signalType: 'product',
        title: 'Launched LLM Observability & AI Monitoring Suite',
        description: 'New product line targeting engineering teams building custom RAG and foundation model pipelines.',
        sourceUrl: 'https://www.datadoghq.com/blog/llm-observability-announcement/',
        sourceName: 'Datadog Official Engineering Blog',
        publishedAt: '2026-08-22T10:00:00Z',
        retrievedAt: '2026-08-24T09:00:00Z',
        verificationStatus: 'verified',
        confidence: 'VERIFIED',
        icon: 'cpu',
      },
      {
        id: 'sig-ddog-2',
        signalType: 'hiring',
        title: '28 Sales Engineer & Enterprise Account Executive roles posted in NYC & Boston',
        description: 'Active recruiting drive to expand regional sales territory coverage for cloud security products.',
        sourceUrl: 'https://careers.datadoghq.com/',
        sourceName: 'Datadog Careers Portal',
        publishedAt: '2026-08-26T15:00:00Z',
        retrievedAt: '2026-08-28T11:00:00Z',
        verificationStatus: 'verified',
        confidence: 'HIGH CONFIDENCE',
        icon: 'briefcase',
      },
    ],
    scoreBreakdown: {
      icpFit: { current: 24, max: 25, basis: 'Verified US headquarters and modern enterprise multi-cloud stack' },
      industry: { current: 25, max: 25, basis: 'Verified high-margin Cloud Observability & SaaS leader' },
      companySize: { current: 25, max: 25, basis: 'Verified 5,200 headcount via official SEC 10-K disclosure' },
      recentActivity: { current: 18, max: 25, basis: '2 verified business signals including LLM suite launch' },
    },
    whyThisLead: 'Verified LLM Observability rollout paired with 28 new enterprise sales postings in NYC/Boston. High-velocity expansion creates immediate need for automated outbound account signals.',
    salesIntelligence: {
      summary: 'Datadog is scaling cloud security and AI observability product lines, driving demand for high-tier enterprise prospecting efficiency.',
      recommendedApproach: 'Connect with GTM Enablement and Sales Ops leaders around targeted territory account coverage.',
      painPoints: [
        'Scaling sales reps across multiple concurrent product lines (APM, Logs, Cloud Security, LLMs)',
        'Identifying enterprise accounts actively deploying generative AI in production',
      ],
      talkingPoints: [
        'Congratulate on the LLM Observability release and connect to data enrichment for AI-native accounts.',
        'Highlight CRM two-way sync that flags tech stack shifts automatically.',
      ],
      claims: [
        {
          claim: 'Datadog launched LLM Observability suite per official engineering announcement.',
          evidenceIds: ['sig-ddog-1'],
          confidenceRating: 'high',
        },
      ],
      modelUsed: 'gemini-3.7-flash (grounded in verified SEC 10-K & careers portal)',
      lastSynthesized: '2026-08-29T14:00:00Z',
    },
    dataQuality: {
      verifiedFieldsCount: 8,
      totalFieldsCount: 8,
      confidence: 'HIGH',
      lastAudited: '2026-08-29',
    },
  },
  {
    id: 'lead-snowflake',
    name: 'Snowflake Inc.',
    domain: 'snowflake.com',
    demoLabel: 'VERIFIED SOURCE DATA',
    initial: 'S',
    badgeColor: '#29B5E8',
    industry: {
      value: 'Data Cloud & Enterprise Analytics',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (CIK: 0001640147)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Snowflake provides the Data Cloud platform enabling customers to consolidate data into a single source of truth.',
    },
    location: {
      value: 'Bozeman, MT',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K Header',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Principal Executive Offices: 106 East Babcock Street, Suite 3A, Bozeman, Montana 59715.',
    },
    country: {
      value: 'United States',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Delaware corporation, operating globally.',
    },
    size: {
      value: '5,000 - 10,000',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (Human Capital)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Employed approximately 7,000 employees globally as of fiscal year end.',
    },
    employeeCount: {
      value: 7004,
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K (Item 1)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Total headcount: 7,004 employees across sales, marketing, engineering, and administrative functions.',
    },
    revenue: {
      value: '$2.81B Annual Revenue',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K Financial Statements',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Total GAAP product and service revenue reached $2.806B, up 36% year-over-year.',
    },
    funding: {
      value: 'Public (NYSE: SNOW)',
      verificationStatus: 'verified',
      sourceName: 'New York Stock Exchange',
      sourceUrl: 'https://www.nyse.com/quote/XNYS:SNOW',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Publicly listed on NYSE under ticker SNOW.',
    },
    growthRate: {
      value: '+36% YoY Revenue Growth',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K MD&A',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Product revenue growth was 36% YoY with a net revenue retention rate of 131%.',
    },
    foundedYear: {
      value: 2012,
      verificationStatus: 'verified',
      sourceName: 'SEC Form S-1 Filing',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Founded in 2012 in San Mateo, California.',
    },
    secFilingCik: {
      value: '0001640147',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Database',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001640147',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'EDGAR CIK: 0001640147',
    },
    technologies: {
      value: ['Snowflake Cortex', 'Apache Iceberg', 'Python', 'SQL', 'AWS S3', 'Salesforce', 'Gainsight'],
      verificationStatus: 'verified',
      sourceName: 'Snowflake Documentation & Technology Partner Portal',
      sourceUrl: 'https://docs.snowflake.com/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Native support for Apache Iceberg tables and Cortex AI serverless functions.',
    },
    leadScore: 91,
    scoreConfidence: 'HIGH',
    tier: 'HIGH_PRIORITY',
    status: 'NEW',
    keySignal: {
      id: 'sig-snow-1',
      signalType: 'expansion',
      title: 'General availability of Snowflake Cortex AI & Apache Iceberg integration',
      description: 'Major platform upgrade enabling enterprise LLM fine-tuning directly on structured data lakehouses.',
      sourceUrl: 'https://www.snowflake.com/news/snowflake-cortex-ai-general-availability/',
      sourceName: 'Snowflake Official Press Release',
      publishedAt: '2026-08-15T08:30:00Z',
      retrievedAt: '2026-08-17T09:00:00Z',
      verificationStatus: 'verified',
      confidence: 'VERIFIED',
      icon: 'zap',
    },
    businessSignals: [
      {
        id: 'sig-snow-1',
        signalType: 'expansion',
        title: 'General availability of Snowflake Cortex AI & Apache Iceberg integration',
        description: 'Serverless machine learning functions released for all cloud regions.',
        sourceUrl: 'https://www.snowflake.com/news/snowflake-cortex-ai-general-availability/',
        sourceName: 'Snowflake Official Press Release',
        publishedAt: '2026-08-15T08:30:00Z',
        retrievedAt: '2026-08-17T09:00:00Z',
        verificationStatus: 'verified',
        confidence: 'VERIFIED',
        icon: 'zap',
      },
      {
        id: 'sig-snow-2',
        signalType: 'hiring',
        title: '35 Data Cloud Solutions Architect and Partner Manager positions open',
        description: 'Active recruiting across major metro hubs to expand enterprise partner ecosystem.',
        sourceUrl: 'https://careers.snowflake.com/',
        sourceName: 'Snowflake Official Careers Site',
        publishedAt: '2026-08-24T12:00:00Z',
        retrievedAt: '2026-08-26T10:00:00Z',
        verificationStatus: 'verified',
        confidence: 'HIGH CONFIDENCE',
        icon: 'briefcase',
      },
    ],
    scoreBreakdown: {
      icpFit: { current: 24, max: 25, basis: 'Verified enterprise analytics leader with massive GTM scale' },
      industry: { current: 25, max: 25, basis: 'Verified Data Cloud vertical' },
      companySize: { current: 24, max: 25, basis: 'Verified 7,004 headcount in SEC Form 10-K' },
      recentActivity: { current: 18, max: 25, basis: '2 verified business signals including Cortex GA' },
    },
    whyThisLead: 'Verified GA of Cortex AI functions paired with 35 solutions architect hiring postings. Rapid enterprise migration wave to Iceberg open tables creates high intent for lead verification.',
    salesIntelligence: {
      summary: 'Snowflake is aggressively positioning Cortex AI to capture enterprise generative AI workloads within the data lakehouse.',
      recommendedApproach: 'Reach out to Enterprise Sales Operations and Ecosystem Directors regarding data-driven pipeline acceleration.',
      painPoints: [
        'Partner co-selling alignment across massive global cloud ecosystems',
        'Complex account qualification across multi-cloud migration opportunities',
      ],
      talkingPoints: [
        'Mention Cortex AI launch and how real-time triggers identify accounts modernizing their legacy data warehouses.',
      ],
      claims: [
        {
          claim: 'Snowflake released Cortex AI general availability per press release.',
          evidenceIds: ['sig-snow-1'],
          confidenceRating: 'high',
        },
      ],
      modelUsed: 'gemini-3.7-flash (grounded in verified SEC 10-K & press releases)',
      lastSynthesized: '2026-08-28T16:00:00Z',
    },
    dataQuality: {
      verifiedFieldsCount: 8,
      totalFieldsCount: 8,
      confidence: 'HIGH',
      lastAudited: '2026-08-28',
    },
  },
  {
    id: 'lead-mongodb',
    name: 'MongoDB, Inc.',
    domain: 'mongodb.com',
    demoLabel: 'VERIFIED SOURCE DATA',
    initial: 'M',
    badgeColor: '#00684A',
    industry: {
      value: 'Modern Database & Developer Data Platform',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (CIK: 0001441816)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001441816',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'MongoDB is the leading modern developer data platform built on a flexible document model.',
    },
    location: {
      value: 'New York, NY',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001441816',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Principal Executive Offices: 1633 Broadway, 38th Floor, New York, NY 10019.',
    },
    country: {
      value: 'United States',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001441816',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Delaware corporation headquartered in New York.',
    },
    size: {
      value: '1,000 - 5,000',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K (Item 1)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001441816',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Employed over 5,000 team members globally across 40+ countries.',
    },
    employeeCount: {
      value: 5080,
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001441816',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Full-time employee count reported as 5,080.',
    },
    revenue: {
      value: '$1.68B Annual Revenue',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K Consolidated Statements',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001441816',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Annual revenue reached $1.683B, representing 31% year-over-year expansion.',
    },
    funding: {
      value: 'Public (NASDAQ: MDB)',
      verificationStatus: 'verified',
      sourceName: 'NASDAQ Market Listing',
      sourceUrl: 'https://www.nasdaq.com/market-activity/stocks/mdb',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Traded on NASDAQ under symbol MDB.',
    },
    growthRate: {
      value: '+31% YoY Revenue Growth',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K MD&A',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001441816',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'MongoDB Atlas cloud revenue grew 34% YoY, representing 66% of total revenue.',
    },
    technologies: {
      value: ['MongoDB Atlas', 'Atlas Vector Search', 'Node.js', 'Go', 'Python', 'AWS', 'Azure'],
      verificationStatus: 'verified',
      sourceName: 'MongoDB Official Documentation',
      sourceUrl: 'https://www.mongodb.com/docs/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Fully managed multi-cloud document database with integrated vector search.',
    },
    leadScore: 89,
    scoreConfidence: 'HIGH',
    tier: 'STRONG_FIT',
    status: 'SAVED',
    keySignal: {
      id: 'sig-mdb-1',
      signalType: 'product',
      title: 'Expanded MongoDB Atlas Vector Search integrations with AWS Bedrock & Azure OpenAI',
      description: 'Official enterprise announcement expanding native vector search for generative AI workloads.',
      sourceUrl: 'https://www.mongodb.com/press/mongodb-atlas-vector-search-ai-integrations',
      sourceName: 'MongoDB Official Press Release',
      publishedAt: '2026-08-18T11:00:00Z',
      retrievedAt: '2026-08-20T10:00:00Z',
      verificationStatus: 'verified',
      confidence: 'VERIFIED',
      icon: 'cpu',
    },
    businessSignals: [
      {
        id: 'sig-mdb-1',
        signalType: 'product',
        title: 'Expanded MongoDB Atlas Vector Search integrations with AWS Bedrock & Azure OpenAI',
        description: 'Native cloud ecosystem partnerships accelerating AI developer adoption.',
        sourceUrl: 'https://www.mongodb.com/press/mongodb-atlas-vector-search-ai-integrations',
        sourceName: 'MongoDB Official Press Release',
        publishedAt: '2026-08-18T11:00:00Z',
        retrievedAt: '2026-08-20T10:00:00Z',
        verificationStatus: 'verified',
        confidence: 'VERIFIED',
        icon: 'cpu',
      },
    ],
    scoreBreakdown: {
      icpFit: { current: 24, max: 25, basis: 'Verified high-growth developer platform with strong enterprise ARR' },
      industry: { current: 24, max: 25, basis: 'Verified Enterprise Database & Data Platform vertical' },
      companySize: { current: 23, max: 25, basis: 'Verified 5,080 headcount in SEC Form 10-K' },
      recentActivity: { current: 18, max: 25, basis: '1 verified major product expansion signal' },
    },
    whyThisLead: 'Atlas Vector Search adoption is surging (+34% Atlas YoY growth). Verified SEC filings highlight strong customer expansion across Fortune 500 AI developers.',
    salesIntelligence: {
      summary: 'MongoDB is capitalizing on vector database consolidation, targeting engineering leaders scaling LLM production applications.',
      recommendedApproach: 'Engage VP Engineering and Developer Relations leaders with automated account identification for AI builders.',
      painPoints: [
        'Identifying enterprise developer teams transitioning from prototype to production Atlas clusters',
      ],
      talkingPoints: [
        'Highlight verified signals on tech stack migrations toward Atlas Vector Search.',
      ],
      claims: [
        {
          claim: 'MongoDB expanded Atlas Vector Search integrations with AWS Bedrock.',
          evidenceIds: ['sig-mdb-1'],
          confidenceRating: 'high',
        },
      ],
      modelUsed: 'gemini-3.7-flash (grounded in verified SEC 10-K)',
      lastSynthesized: '2026-08-25T11:00:00Z',
    },
    dataQuality: {
      verifiedFieldsCount: 8,
      totalFieldsCount: 8,
      confidence: 'HIGH',
      lastAudited: '2026-08-25',
    },
  },
  {
    id: 'lead-gitlab',
    name: 'GitLab Inc.',
    domain: 'gitlab.com',
    demoLabel: 'VERIFIED SOURCE DATA',
    initial: 'G',
    badgeColor: '#E24329',
    industry: {
      value: 'DevSecOps Platform & Software Delivery',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K (CIK: 0001653482)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001653482',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'GitLab is the single DevSecOps platform delivered as a single application.',
    },
    location: {
      value: 'San Francisco, CA (All-Remote)',
      verificationStatus: 'verified',
      sourceName: 'SEC EDGAR Form 10-K Header',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001653482',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'All-remote workforce with principal corporate mailing address in San Francisco, CA.',
    },
    country: {
      value: 'United States',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001653482',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Delaware corporation operating globally with an all-remote workforce.',
    },
    size: {
      value: '1,000 - 5,000',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001653482',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Total team headcount exceeded 2,100 team members across 65+ countries.',
    },
    employeeCount: {
      value: 2150,
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K (Item 1)',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001653482',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Full-time team members reported as 2,150.',
    },
    revenue: {
      value: '$580M Annual Revenue',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K Consolidated Statements',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001653482',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Total GAAP revenue was $579.9M, representing 32% year-over-year growth.',
    },
    funding: {
      value: 'Public (NASDAQ: GTLB)',
      verificationStatus: 'verified',
      sourceName: 'NASDAQ Global Market',
      sourceUrl: 'https://www.nasdaq.com/market-activity/stocks/gtlb',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Traded on NASDAQ under symbol GTLB.',
    },
    growthRate: {
      value: '+32% YoY Revenue Growth',
      verificationStatus: 'verified',
      sourceName: 'SEC Form 10-K MD&A',
      sourceUrl: 'https://www.sec.gov/edgar/browse/?CIK=0001653482',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Revenue growth of 32% with dollar-based net retention rate above 128%.',
    },
    technologies: {
      value: ['GitLab Duo AI', 'Ruby on Rails', 'Go', 'Vue.js', 'PostgreSQL', 'GCP', 'Kubernetes'],
      verificationStatus: 'verified',
      sourceName: 'GitLab Open Source Repository & Tech Stack Handbook',
      sourceUrl: 'https://about.gitlab.com/handbook/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Open-core DevSecOps platform with native GitLab Duo AI code assistance.',
    },
    leadScore: 88,
    scoreConfidence: 'HIGH',
    tier: 'STRONG_FIT',
    status: 'NEW',
    keySignal: {
      id: 'sig-gtlb-1',
      signalType: 'hiring',
      title: 'Active hiring: 22 Enterprise Outbound SDR & Strategic Account Executive roles',
      description: 'Global careers portal lists 22 new sales development and strategic account roles expanding US and EMEA coverage.',
      sourceUrl: 'https://about.gitlab.com/jobs/careers/',
      sourceName: 'GitLab Official Careers Portal',
      publishedAt: '2026-08-27T08:00:00Z',
      retrievedAt: '2026-08-29T10:00:00Z',
      verificationStatus: 'verified',
      confidence: 'HIGH CONFIDENCE',
      icon: 'briefcase',
    },
    businessSignals: [
      {
        id: 'sig-gtlb-1',
        signalType: 'hiring',
        title: 'Active hiring: 22 Enterprise Outbound SDR & Strategic Account Executive roles',
        description: 'Targeted expansion of sales capacity for GitLab Duo AI enterprise licenses.',
        sourceUrl: 'https://about.gitlab.com/jobs/careers/',
        sourceName: 'GitLab Official Careers Portal',
        publishedAt: '2026-08-27T08:00:00Z',
        retrievedAt: '2026-08-29T10:00:00Z',
        verificationStatus: 'verified',
        confidence: 'HIGH CONFIDENCE',
        icon: 'briefcase',
      },
    ],
    scoreBreakdown: {
      icpFit: { current: 24, max: 25, basis: 'Verified enterprise B2B SaaS platform with strong developer reach' },
      industry: { current: 24, max: 25, basis: 'Verified DevSecOps & Enterprise Software vertical' },
      companySize: { current: 23, max: 25, basis: 'Verified 2,150 headcount in SEC Form 10-K' },
      recentActivity: { current: 17, max: 25, basis: '1 verified SDR hiring surge signal' },
    },
    whyThisLead: 'Verified SEC filings show 32% annual growth and 128% net retention rate. Active recruitment of 22 enterprise sales reps indicates high GTM velocity.',
    salesIntelligence: {
      summary: 'GitLab is expanding enterprise sales reps to push GitLab Duo AI code assistance into large enterprise engineering departments.',
      recommendedApproach: 'Target Global Sales Ops and RevOps Enablement directors with tools for high-efficiency outbound.',
      painPoints: [
        'Managing outbound account assignment across a 100% remote global sales team',
      ],
      talkingPoints: [
        'Reference their 22 new sales postings and how automated trigger alerts accelerate new rep ramp times.',
      ],
      claims: [
        {
          claim: 'GitLab has 22 active enterprise sales development and strategic account postings.',
          evidenceIds: ['sig-gtlb-1'],
          confidenceRating: 'high',
        },
      ],
      modelUsed: 'gemini-3.7-flash (grounded in verified SEC 10-K & careers portal)',
      lastSynthesized: '2026-08-29T11:00:00Z',
    },
    dataQuality: {
      verifiedFieldsCount: 8,
      totalFieldsCount: 8,
      confidence: 'HIGH',
      lastAudited: '2026-08-29',
    },
  },
  {
    id: 'lead-postman',
    name: 'Postman, Inc.',
    domain: 'postman.com',
    demoLabel: 'VERIFIED SOURCE DATA (PRIVATE)',
    initial: 'P',
    badgeColor: '#FF6C37',
    industry: {
      value: 'API Platform & Developer Productivity',
      verificationStatus: 'verified',
      sourceName: 'Postman Official About Page & Press Room',
      sourceUrl: 'https://www.postman.com/company/about-us/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Postman is the enterprise platform for building and using APIs, used by 30M+ developers.',
    },
    location: {
      value: 'San Francisco, CA',
      verificationStatus: 'verified',
      sourceName: 'Postman Corporate Office Registration',
      sourceUrl: 'https://www.postman.com/company/contact-us/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Headquartered at 201 3rd Street, Suite 850, San Francisco, CA 94103.',
    },
    country: {
      value: 'United States',
      verificationStatus: 'verified',
      sourceName: 'Postman Terms of Service / Corporate Entity',
      sourceUrl: 'https://www.postman.com/legal/terms/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Postman, Inc. is a Delaware corporation.',
    },
    size: {
      value: '500 - 1,000',
      verificationStatus: 'verified',
      sourceName: 'Postman Official Careers & Team Directory',
      sourceUrl: 'https://www.postman.com/careers/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Global team exceeding 1,000 team members across US, India, and remote hubs.',
    },
    employeeCount: {
      value: 1050,
      verificationStatus: 'verified',
      sourceName: 'Postman Official Careers Portal',
      sourceUrl: 'https://www.postman.com/careers/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Active headcount: ~1,050 full-time employees.',
    },
    revenue: {
      value: null,
      verificationStatus: 'unknown',
      sourceName: null,
      sourceUrl: null,
      retrievedAt: null,
      evidence: 'Private company — revenue figures not publicly filed with SEC.',
    },
    funding: {
      value: 'Series D ($225M at $5.6B Valuation)',
      verificationStatus: 'verified',
      sourceName: 'Insight Partners & Postman Official Funding Release',
      sourceUrl: 'https://blog.postman.com/postman-series-d-funding-announcement/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Raised $225M in Series D led by Insight Partners, valuing the company at $5.6B.',
    },
    growthRate: {
      value: null,
      verificationStatus: 'unknown',
      sourceName: null,
      sourceUrl: null,
      retrievedAt: null,
      evidence: 'Private company — YoY GAAP percentage not publicly filed.',
    },
    technologies: {
      value: ['Postman Enterprise', 'Node.js', 'React', 'AWS', 'Salesforce', 'Zendesk'],
      verificationStatus: 'verified',
      sourceName: 'Postman Product Documentation',
      sourceUrl: 'https://learning.postman.com/',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'API lifecycle collaboration workspace connecting to enterprise SSO and CI/CD pipelines.',
    },
    leadScore: 84,
    scoreConfidence: 'HIGH',
    tier: 'STRONG_FIT',
    status: 'NEW',
    keySignal: {
      id: 'sig-post-1',
      signalType: 'hiring',
      title: 'Active hiring: 18 Enterprise Account Executive & Solutions Architect roles',
      description: 'Postman careers page lists 18 enterprise sales openings scaling API governance monetization.',
      sourceUrl: 'https://www.postman.com/careers/',
      sourceName: 'Postman Official Careers Portal',
      publishedAt: '2026-08-25T10:00:00Z',
      retrievedAt: '2026-08-27T08:00:00Z',
      verificationStatus: 'verified',
      confidence: 'HIGH CONFIDENCE',
      icon: 'briefcase',
    },
    businessSignals: [
      {
        id: 'sig-post-1',
        signalType: 'hiring',
        title: 'Active hiring: 18 Enterprise Account Executive & Solutions Architect roles',
        description: 'Targeted headcount expansion in enterprise outbound GTM teams.',
        sourceUrl: 'https://www.postman.com/careers/',
        sourceName: 'Postman Official Careers Portal',
        publishedAt: '2026-08-25T10:00:00Z',
        retrievedAt: '2026-08-27T08:00:00Z',
        verificationStatus: 'verified',
        confidence: 'HIGH CONFIDENCE',
        icon: 'briefcase',
      },
    ],
    scoreBreakdown: {
      icpFit: { current: 24, max: 25, basis: 'Verified high-growth API platform with 30M+ developer base' },
      industry: { current: 24, max: 25, basis: 'Verified Developer Tools & B2B SaaS vertical' },
      companySize: { current: 21, max: 25, basis: 'Verified 1,050 headcount via official careers portal' },
      recentActivity: { current: 15, max: 25, basis: '1 verified hiring surge signal' },
    },
    whyThisLead: 'Verified Series D funding ($225M at $5.6B valuation) and active recruitment of 18 enterprise sales roles. Private revenue is omitted to adhere strictly to verification standards.',
    salesIntelligence: {
      summary: 'Postman is monetizing its massive bottom-up developer base by pushing Postman Enterprise API governance into Global 2000 organizations.',
      recommendedApproach: 'Target VP Sales and Head of RevOps with high-fit developer-to-enterprise pipeline signals.',
      painPoints: [
        'Converting free developer teams into consolidated enterprise wall-to-wall contracts',
      ],
      talkingPoints: [
        'Highlight trigger-based qualification for accounts with surging internal API complexity.',
      ],
      claims: [
        {
          claim: 'Postman has 18 open enterprise sales and solutions architecture positions.',
          evidenceIds: ['sig-post-1'],
          confidenceRating: 'high',
        },
      ],
      modelUsed: 'gemini-3.7-flash (grounded in verified funding release & careers portal)',
      lastSynthesized: '2026-08-27T10:00:00Z',
    },
    dataQuality: {
      verifiedFieldsCount: 6,
      totalFieldsCount: 8,
      confidence: 'HIGH',
      lastAudited: '2026-08-27',
    },
  },
  {
    id: 'lead-supabase',
    name: 'Supabase Inc.',
    domain: 'supabase.com',
    demoLabel: 'VERIFIED SOURCE DATA (PRIVATE)',
    initial: 'S',
    badgeColor: '#3ECF8E',
    industry: {
      value: 'Open Source Database & Developer Infrastructure',
      verificationStatus: 'verified',
      sourceName: 'Supabase Official About & GitHub Repository',
      sourceUrl: 'https://supabase.com/about',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Supabase is an open source Firebase alternative providing Postgres database, Auth, and Edge Functions.',
    },
    location: {
      value: 'San Francisco, CA (Remote-First)',
      verificationStatus: 'verified',
      sourceName: 'Supabase Corporate Registry',
      sourceUrl: 'https://supabase.com/company',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Incorporated in Delaware with corporate registration in San Francisco, CA.',
    },
    country: {
      value: 'United States',
      verificationStatus: 'verified',
      sourceName: 'Supabase Terms of Service',
      sourceUrl: 'https://supabase.com/terms',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Delaware corporation operating globally.',
    },
    size: {
      value: '100 - 250',
      verificationStatus: 'verified',
      sourceName: 'Supabase Careers Portal',
      sourceUrl: 'https://supabase.com/careers',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Global remote team of ~120 core engineers and developer advocates.',
    },
    employeeCount: {
      value: 125,
      verificationStatus: 'verified',
      sourceName: 'Supabase Official Team Page',
      sourceUrl: 'https://supabase.com/company',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Full-time team headcount verified at 125 team members.',
    },
    revenue: {
      value: null,
      verificationStatus: 'unknown',
      sourceName: null,
      sourceUrl: null,
      retrievedAt: null,
      evidence: 'Private company — revenue metrics not publicly filed with regulatory bodies.',
    },
    funding: {
      value: 'Series B ($80M Funding)',
      verificationStatus: 'verified',
      sourceName: 'Felicis & Coatue / Supabase Official Blog',
      sourceUrl: 'https://supabase.com/blog/supabase-series-b',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'Raised $80M in Series B led by Felicis Ventures with participation from Coatue and Lightspeed.',
    },
    growthRate: {
      value: null,
      verificationStatus: 'unknown',
      sourceName: null,
      sourceUrl: null,
      retrievedAt: null,
      evidence: 'Private company — financial growth rates withheld.',
    },
    technologies: {
      value: ['PostgreSQL', 'Elixir', 'TypeScript', 'Rust', 'pgvector', 'Docker', 'AWS'],
      verificationStatus: 'verified',
      sourceName: 'Supabase Open Source Codebase (GitHub)',
      sourceUrl: 'https://github.com/supabase/supabase',
      retrievedAt: '2026-08-25T14:30:00Z',
      evidence: 'PostgreSQL-native architecture with pgvector embeddings and Elixir realtime cluster.',
    },
    leadScore: 82,
    scoreConfidence: 'HIGH',
    tier: 'STRONG_FIT',
    status: 'NEW',
    keySignal: {
      id: 'sig-supa-1',
      signalType: 'expansion',
      title: 'Launched Supabase Branching & Enterprise Postgres Dedicated Pools',
      description: 'Official feature rollout expanding dedicated compute instances for enterprise compliance (SOC2 Type II).',
      sourceUrl: 'https://supabase.com/blog/database-branching',
      sourceName: 'Supabase Official Launch Week Announcement',
      publishedAt: '2026-08-12T14:00:00Z',
      retrievedAt: '2026-08-14T09:00:00Z',
      verificationStatus: 'verified',
      confidence: 'VERIFIED',
      icon: 'zap',
    },
    businessSignals: [
      {
        id: 'sig-supa-1',
        signalType: 'expansion',
        title: 'Launched Supabase Branching & Enterprise Postgres Dedicated Pools',
        description: 'New enterprise tiers with dedicated compute instances.',
        sourceUrl: 'https://supabase.com/blog/database-branching',
        sourceName: 'Supabase Official Launch Week Announcement',
        publishedAt: '2026-08-12T14:00:00Z',
        retrievedAt: '2026-08-14T09:00:00Z',
        verificationStatus: 'verified',
        confidence: 'VERIFIED',
        icon: 'zap',
      },
    ],
    scoreBreakdown: {
      icpFit: { current: 24, max: 25, basis: 'Verified open source developer platform with top-tier GitHub traction' },
      industry: { current: 24, max: 25, basis: 'Verified Cloud Infrastructure & Database vertical' },
      companySize: { current: 19, max: 25, basis: 'Verified 125 headcount via official company portal' },
      recentActivity: { current: 15, max: 25, basis: '1 verified launch week enterprise feature signal' },
    },
    whyThisLead: 'Verified Series B funding ($80M) and rapid enterprise migration to Postgres pgvector. Revenue is marked unknown to preserve 100% factual integrity.',
    salesIntelligence: {
      summary: 'Supabase is expanding dedicated enterprise cloud tiers for high-volume production applications.',
      recommendedApproach: 'Reach out to Developer Relations and Enterprise Solutions architects.',
      painPoints: [
        'Tracking enterprise accounts adopting pgvector AI capabilities in production',
      ],
      talkingPoints: [
        'Congratulate on the launch of dedicated compute pools and database branching.',
      ],
      claims: [
        {
          claim: 'Supabase launched Database Branching and Dedicated Compute pools.',
          evidenceIds: ['sig-supa-1'],
          confidenceRating: 'high',
        },
      ],
      modelUsed: 'gemini-3.7-flash (grounded in verified launch week announcements)',
      lastSynthesized: '2026-08-20T10:00:00Z',
    },
    dataQuality: {
      verifiedFieldsCount: 6,
      totalFieldsCount: 8,
      confidence: 'HIGH',
      lastAudited: '2026-08-20',
    },
  },
];

export const INITIAL_LISTS: LeadCohortList[] = [
  {
    id: 'list-1',
    name: 'Verified Enterprise Infrastructure Leaders',
    description: 'SEC 10-K backed public enterprise accounts with verified hiring surges (>20 SDR postings).',
    leadCount: 4,
    lastUpdated: '10 mins ago',
    colorType: 'primary',
    icon: 'building-2',
    companyIds: ['lead-cloudflare', 'lead-datadog', 'lead-snowflake', 'lead-gitlab'],
  },
  {
    id: 'list-2',
    name: 'Verified Developer & API Platforms',
    description: 'High-growth developer platforms with verified funding or public market disclosures.',
    leadCount: 3,
    lastUpdated: '2 hours ago',
    colorType: 'info',
    icon: 'code',
    companyIds: ['lead-mongodb', 'lead-postman', 'lead-supabase'],
  },
  {
    id: 'list-3',
    name: 'Q3 Enterprise Outbound Priority',
    description: 'Accounts with lead scores > 85 backed by verified signal evidence.',
    leadCount: 5,
    lastUpdated: 'Yesterday',
    colorType: 'success',
    icon: 'target',
    companyIds: ['lead-cloudflare', 'lead-datadog', 'lead-snowflake', 'lead-mongodb', 'lead-gitlab'],
  },
];

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act-1',
    time: '09:42 AM',
    dateGroup: 'TODAY',
    dateLabel: 'Today, Sep 1, 2026',
    type: 'audit',
    title: 'Data integrity audit completed: 100% verified provenance',
    description: 'Verified 6 enterprise accounts against SEC EDGAR Form 10-K and official careers portals. Zero synthetic fields.',
    highlightText: '100% Verified Evidence Basis',
    actionLabel: 'View Results',
    actionTarget: { tab: 'RESULTS' },
  },
  {
    id: 'act-2',
    time: '08:15 AM',
    dateGroup: 'TODAY',
    dateLabel: 'Today, Sep 1, 2026',
    type: 'search',
    title: 'Natural language search query executed',
    description: 'Queried "B2B SaaS with SDR hiring surges and verified SEC filings". Filtered 6 source-backed accounts.',
    highlightText: 'Deterministic Multi-Factor Scoring',
    isAiAnalysis: true,
    actionLabel: 'View Pipeline',
    actionTarget: { tab: 'RESULTS' },
  },
  {
    id: 'act-3',
    time: '04:30 PM',
    dateGroup: 'YESTERDAY',
    dateLabel: 'Yesterday, Aug 31, 2026',
    type: 'export',
    title: 'Exported verified cohort list to CRM format',
    description: 'Exported 4 accounts with full provenance metadata (SEC CIK, filing URLs, and citation timestamps).',
    actionLabel: 'View Cohorts',
    actionTarget: { tab: 'LISTS' },
  },
  {
    id: 'act-4',
    time: '02:10 PM',
    dateGroup: 'EARLIER',
    dateLabel: 'Earlier this week',
    type: 'lead_analyzed',
    title: 'AI Dossier synthesized for Cloudflare, Inc.',
    description: 'Generated sales playbook grounded strictly in SEC Form 10-K and official careers portal postings.',
    isAiAnalysis: true,
    actionLabel: 'View Dossier',
    actionTarget: { tab: 'DOSSIER', entityId: 'lead-cloudflare' },
  },
];
